In [37]:
import numpy as np
arr1 = np.array([[0,1,2],[3,5,6],[7,8,9],[4,8,6],[6,9,3]])
arr2 = arr1.reshape(3,5)
print(arr1)
print(arr1[:,1:3])
for row in arr1:
    print(row[1])

arr3 = np.arange(12).reshape(3,4)
print(arr3)

n= np.arange(3,15,4).reshape(1,3)
print(n)

[[0 1 2]
 [3 5 6]
 [7 8 9]
 [4 8 6]
 [6 9 3]]
[[1 2]
 [5 6]
 [8 9]
 [8 6]
 [9 3]]
1
5
8
8
9
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 3  7 11]]
